[workspace]

members = [
    "crates/bpm",
    "crates/bpmd",
    "crates/bpmpack",
    "crates/hash_stream",
    "crates/hashdir",
    "crates/httpsearch",
    "crates/zstd_patch",
    "crates/walk_example",
]
