cache_dir = "${BPM}/../../bpm/cache"
database = "${BPM}/../../bpm/db"
use_default_target = true

[providers]
main = "http://localhost:8000/pkg"
#base = "fs:///home/hepta/bpm/pkgs"

[mount]
TARGET = "${BPM}/../../bpm/install"
EXTENSIONS = "${BPM}/../../bpm/install/extensions"
#honk       = "${BPM}/../honk"
